"""Atomic event ingestion: idempotency claim + job persistence + ready-
stream enqueue as a single Redis Lua script.

Replaces the three-round-trip sequence (`IdempotencyGuard.claim` ->
`JobStore.save` -> `ReadyQueue.enqueue`) `POST /api/v1/events` used
through Phases 2-4. That sequence had a real bug: if the process died
between the idempotency claim and the job save, the idempotency key
would permanently point at a task_id with no job record -- and every
subsequent request with that same key would hit the "job missing, fall
through as fresh" branch, silently creating a brand-new task each time
without ever updating the idempotency mapping. Not a one-time orphan:
**unbounded duplicate dispatch for that key until the TTL expired.**

A single atomic script closes this structurally: the claim and the
write happen as one indivisible unit, so there is no window in which
the idempotency key can point at a job that doesn't exist. `IdempotencyGuard`
and `ReadyQueue.enqueue` remain correct, independently usable code (not
removed) -- they're simply no longer wired into this specific route,
which now goes through `EventIngestor.ingest` instead.
"""

from __future__ import annotations

from dataclasses import dataclass
from uuid import UUID

import redis.asyncio as redis

from dart.core.config import RedisSettings
from dart.models.task import WebhookTask

# KEYS[1] = idempotency key (dart:idempotency:<idempotency_key>)
# KEYS[2] = job hash key (dart:job:<task_id>)
# KEYS[3] = ready stream key (dart:queue:ready)
# ARGV[1] = task_id (the candidate task_id generated by the caller)
# ARGV[2] = idempotency key TTL, seconds
# ARGV[3..] = flattened WebhookTask.to_redis_hash() field/value pairs,
#             i.e. [field1, value1, field2, value2, ...]
#
# Returns {task_id, is_new} as a two-element array:
#   - is_new = 1: a fresh ingestion. task_id echoes ARGV[1]; the job hash
#     was written and the task_id was enqueued onto the ready stream.
#   - is_new = 0: a duplicate. task_id is the ORIGINAL request's task_id
#     (not ARGV[1]) -- nothing was written on this call.
_INGEST_EVENT_SCRIPT = """
local claimed = redis.call('SET', KEYS[1], ARGV[1], 'NX', 'EX', ARGV[2])

if not claimed then
    local existing_task_id = redis.call('GET', KEYS[1])
    if existing_task_id then
        return {existing_task_id, 0}
    end
    -- Extremely narrow race: the key expired between our failed SET NX
    -- and this GET. Reclaim it now and fall through as a fresh
    -- ingestion -- safe because Redis serializes script execution, so
    -- no other caller can be concurrently mid-write at this point.
    redis.call('SET', KEYS[1], ARGV[1], 'EX', ARGV[2])
end

-- Lua 5.1 exposes `unpack` as a global; 5.2+ moved it to `table.unpack`.
-- Covering both makes this robust across whatever Lua build a given
-- Redis/fakeredis backend embeds.
local unpack = unpack or table.unpack

local hset_args = {}
for i = 3, #ARGV do
    table.insert(hset_args, ARGV[i])
end
redis.call('HSET', KEYS[2], unpack(hset_args))
redis.call('XADD', KEYS[3], '*', 'task_id', ARGV[1])

return {ARGV[1], 1}
"""


@dataclass(frozen=True)
class IngestionResult:
    """Outcome of an atomic ingestion attempt."""

    task_id: UUID
    is_duplicate: bool
    """True if `task_id` refers to a PRIOR request's task (the
    idempotency key was already claimed) rather than the task just
    submitted in this call."""


class EventIngestor:
    """Atomically claims an idempotency key, persists the job record,
    and enqueues it onto the ready stream in one Redis round trip -- or,
    if the key is already claimed, reports the existing task_id without
    writing anything."""

    def __init__(self, client: redis.Redis, settings: RedisSettings) -> None:
        self._client = client
        self._idempotency_key_prefix = settings.idempotency_key_prefix
        self._job_key_prefix = settings.job_key_prefix
        self._ready_stream_key = settings.ready_stream_key
        self._ingest_script = client.register_script(_INGEST_EVENT_SCRIPT)

    @staticmethod
    def _flatten_hash(hash_data: dict[str, str]) -> list[str]:
        """`{field: value, ...}` -> `[field, value, field, value, ...]`,
        the flat form Redis Lua's `HSET ... unpack(t)` idiom expects."""
        flattened: list[str] = []
        for field, value in hash_data.items():
            flattened.append(field)
            flattened.append(value)
        return flattened

    async def ingest(
        self, task: WebhookTask, idempotency_ttl_seconds: int
    ) -> IngestionResult:
        """Atomically claim `task.idempotency_key`; if it's unclaimed,
        persist `task` and enqueue it in the same Redis round trip.

        Args:
            task: The fully-constructed candidate task. Not mutated.
            idempotency_ttl_seconds: TTL for the idempotency key itself
                (not the job record, which has no TTL).
        """
        idempotency_key = f"{self._idempotency_key_prefix}{task.idempotency_key}"
        job_key = f"{self._job_key_prefix}{task.task_id}"
        flattened_hash = self._flatten_hash(task.to_redis_hash())

        raw_task_id, is_new_flag = await self._ingest_script(
            keys=[idempotency_key, job_key, self._ready_stream_key],
            args=[str(task.task_id), idempotency_ttl_seconds, *flattened_hash],
        )

        return IngestionResult(
            task_id=UUID(raw_task_id),
            is_duplicate=(int(is_new_flag) == 0),
        )
